### ISSUE TITLE
context-path: /@contextPath@ 不能识别

### ISSUE THREAD

**Issue by MoneZhao** [ZhangYuanSheng1217/RestfulTool#17]
**首先很感谢老哥的更新，工具越来越方便了🙏**

在application.yml里面配置
```yaml
server:
  servlet:
    context-path: /@contextPath@
```
这种依靠maven来替换的context-path，`http 请求工具`不能识别
`http://localhost:8686/@contextPath@/***`
能不能给个输入框可以修改`http 请求工具`的context-path
